#!/bin/bash

date # print date

_app_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

_file="${_app_dir}/domains"

if [ ! -f "${_file}" ];
then
    echo "${_file} does not exists"
    exit 1
fi

while read -r line;
do
    eval "${line}"

    cmd="python ${_app_dir}/main.py -d ${host} -t ping"

    if [ ! "${port}" = "0" ];
    then
        cmd="python ${_app_dir}/main.py -d ${host} -p ${port} -t telnet"
    fi

    echo "${cmd}"

    response=$(eval $cmd 2>&1)

    if [ ! $? -eq 0 ];
    then
        # something is not ok
        if [ ! "`which dmail`" = "" ];
        then
            {
                echo $cmd
                echo $response
                echo "Host: ${host} Port: ${port}"
            } | dmail -s "Monitor Failed"
        else
            echo $cmd
            echo "Failed! Host: ${host} Port: ${port}"
        fi
    fi
done < "${_file}"





